repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.1
  hooks:
    - id: ruff
    - id: ruff-format
- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: ./.venv/bin/pytest tests
    language: system
    types: [python]
    pass_filenames: false
    always_run: true